{
 "title": "Performance data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AOT - Thread count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\".*AOT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JIT - Thread pool items completed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\".*JIT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AOT - Thread pool items completed",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\".*AOT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JIT - Thread counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\".*JIT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "JIT - GC allocations bytes total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*JIT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "JIT - GC objects size bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*JIT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AOT - GC allocations bytes total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*AOT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "AOT - GC objects size bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*AOT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "JIT Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "JIT Compilation time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_jit_compilation_time_nanoseconds_total{job=~\".*JIT.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}