{
 "title": "Scenario 5 dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testIdQuery",
    "label": "Test ID Query",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"test_id\""
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage (s) - rate", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Container - Memory footprint (B)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 }
  },
  { "title": "Container - IO Time spent (s)", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Container performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Scenario 5",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SRS - Request Duration With Startup",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "JIT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "test_scenario::tag", "operator": "=", "value": "scenario5" },
        { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
        { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "SRS-AOT" }
       ]
      },
      {
       "alias": "JIT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "test_scenario::tag", "operator": "=", "value": "scenario5" },
        { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
        { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "SRS-JIT" }
       ]
      }
     ]
    },
    {
     "title": "SRS - Thread Counts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 18, "x": 6, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\".*SRS.*\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "SRS - Thread Completed Items",
     "type": "stat",
     "gridPos": { "h": 4, "w": 18, "x": 6, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\".*SRS.*\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "BPS - GC Duration",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\".*BPS.*\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "BPS - GC Allocations Bytes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*BPS.*\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "BPS - GC Objects Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*BPS.*\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "BPS - GC Heap Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_runtime_dotnet_gc_heap_size_bytes{job=~\".*BPS.*\"}",
       "legendFormat": "{{job}} - {{generation}}"
      }
     ]
    }
   ]
  }
 ]
}