{
 "title": "Scenario 1 dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testIdQuery",
    "label": "Test ID Query",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"test_id\""
   },
   { "name": "serviceName", "query": "SRS,FUS,BPS,EPS" }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CPU Usage (s) - rate", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 } },
  {
   "title": "Container - Memory footprint (B)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 }
  },
  { "title": "Container - IO Time spent (s)", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 } },
  { "title": "Scenario 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Healtheck request duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-AOT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "BPS-AOT" }
     ]
    },
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-JIT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "BPS-AOT" }
     ]
    }
   ]
  },
  {
   "title": "Healtheck request sending duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_sending",
     "query": "SELECT mean(\"value\") FROM \"http_req_sending\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-AOT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "$serviceName-AOT" }
     ]
    },
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_sending",
     "query": "SELECT mean(\"value\") FROM \"http_req_sending\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-JIT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "$serviceName-JIT" }
     ]
    }
   ]
  },
  {
   "title": "SRS - Healtheck requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT cumulative_sum(count(\"value\")) FROM \"http_reqs\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-AOT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=~", "value": "/^$serviceName$/" }
     ]
    },
    {
     "alias": "$tag_dta_service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT cumulative_sum(count(\"value\")) FROM \"http_reqs\" WHERE (\"test_scenario\"::tag = 'scenario1' AND \"dta_service\"::tag = '$serviceName-JIT') AND $timeFilter GROUP BY time($__interval), \"dta_service\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario1" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=~", "value": "/^$serviceName$/" }
     ]
    }
   ]
  }
 ]
}