{
 "title": "Scenario 2 dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testIdQuery",
    "label": "Test ID Query",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"test_id\""
   }
  ]
 },
 "panels": [
  { "title": "Scenario 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FUS - Request Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "FUS-JIT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario2" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    },
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "FUS-AOT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario2" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    }
   ]
  },
  {
   "title": "FUS - Requests Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "FUS-JIT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario2" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    },
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "FUS-AOT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario2" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    }
   ]
  },
  {
   "title": "FUS - Download REST API Calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_download_rest_calls_counter_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - DB Client Commands Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_client_commands_bytes_read_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - Thread Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - Upload REST API Calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_upload_rest_calls_counter_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - DB Client Commands Duration Sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_client_commands_duration_seconds_sum{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - Thread Completed Items",
   "type": "stat",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - DB Client Commands Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_client_commands_bytes_written_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - GC Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - GC Allocations Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - GC Objects Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - GC Heap Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}} - {{generation}}"
    }
   ]
  }
 ]
}