{
 "title": "Scenario 3 dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testIdQuery",
    "label": "Test ID Query",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"test_id\""
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage (s) - rate", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 } },
  {
   "title": "Container - Memory footprint (B)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 }
  },
  { "title": "Container - IO Time spent (s)", "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 } },
  { "title": "Container performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Scenario 3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "BPS - Thread Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - Thread Completed Items",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "BPS-JIT" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    },
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "dta_service::tag", "operator": "=", "value": "BPS-AOT" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" }
     ]
    }
   ]
  },
  {
   "title": "BPS - Request Duration time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "BPS-JIT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario3" }
     ]
    },
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario3" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "BPS-AOT" }
     ]
    }
   ]
  },
  {
   "title": "BPS - Fibonacci REST API Calls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fibonacci_processed_counter_total{job=\"DTA_JIT_BPS\", test_id=\"$testIdQuery\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "fibonacci_processed_counter_total{job=\"DTA_AOT_BPS\", test_id=\"$testIdQuery\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Allocations Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Objects Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - AOT GC Heap Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{job=\"DTA_AOT_BPS\"}",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "BPS - JIT GC Heap Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{job=\"DTA_JIT_BPS\"}",
     "legendFormat": "{{generation}}"
    }
   ]
  }
 ]
}