{
 "title": "Scenario 4 dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testIdQuery",
    "label": "Test ID Query",
    "query": "SHOW TAG VALUES FROM \"http_req_duration\" WITH KEY = \"test_id\""
   }
  ]
 },
 "panels": [
  { "title": "Scenario 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EPS - Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario4" },
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "EPS-AOT" }
     ]
    },
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "EPS-JIT" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario4" }
     ]
    }
   ]
  },
  {
   "title": "EPS - Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AOT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario4" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "EPS-AOT" }
     ]
    },
    {
     "alias": "JIT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "test_id::tag", "operator": "=~", "value": "/^$testIdQuery$/" },
      { "condition": "AND", "key": "test_scenario::tag", "operator": "=", "value": "scenario4" },
      { "condition": "AND", "key": "dta_service::tag", "operator": "=", "value": "EPS-JIT" }
     ]
    }
   ]
  },
  {
   "title": "BPS - File events consumed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_event_consumed_counter_total{job=\"DTA_AOT_BPS\"}",
     "legendFormat": "AOT"
    },
    {
     "expr": "file_event_consumed_counter_total{job=\"DTA_JIT_BPS\"}",
     "legendFormat": "JIT"
    }
   ]
  },
  {
   "title": "FUS - DB Client Commands Written",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_client_commands_bytes_written_total{job=~\".*FUS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "EPS - File events produced",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_event_produced_counter_total{job=\"DTA_JIT_EPS\"}",
     "legendFormat": "JIT"
    },
    {
     "expr": "batch_event_produced_counter_total{job=\"DTA_AOT_EPS\"}",
     "legendFormat": "AOT"
    }
   ]
  },
  {
   "title": "FUS - gRPC Get File calls",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "get_file_procedure_calls_counter_total{job=\"DTA_JIT_FUS\"}",
     "legendFormat": "JIT"
    },
    {
     "expr": "get_file_procedure_calls_counter_total{job=\"DTA_AOT_FUS\"}",
     "legendFormat": "AOT"
    }
   ]
  },
  {
   "title": "EPS - Thread Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_JIT_EPS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_AOT_EPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "EPS - Thread Completed Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\"DTA_JIT_EPS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\"DTA_AOT_EPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - Thread Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_AOT_BPS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_JIT_BPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - Thread Completed Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=\"DTA_AOT_BPS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=\"DTA_JIT_BPS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - Thread Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_JIT_FUS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count{job=~\"DTA_AOT_FUS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "FUS - Thread Completed Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=\"DTA_JIT_FUS\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total{job=~\"DTA_AOT_FUS\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_duration_nanoseconds_total{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Allocations Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_allocations_size_bytes_total{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Objects Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_objects_size_bytes{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "BPS - GC Heap Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size_bytes{job=~\".*BPS.*\"}",
     "legendFormat": "{{job}} - {{generation}}"
    }
   ]
  }
 ]
}