apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-routing
spec:
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: otel-lgtm
            port:
              number: 3000
      - path: /srs
        pathType: Prefix
        backend:
          service:
            name: srs-service
            port:
              number: 80
      - path: /fus
        pathType: Prefix
        backend:
          service:
            name: fus-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-static
            port:
              number: 80

