FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Services/DTA.FRS/DTA.FRS.csproj", "Services/DTA.FRS/"]
COPY ["Common/DTA.Extensions/DTA.Extensions.csproj", "Common/DTA.Extensions/"]
COPY ["Common/DTA.Models/DTA.Models.csproj", "Common/DTA.Models/"]
RUN dotnet restore "Services/DTA.FRS/DTA.FRS.csproj"

COPY . .
WORKDIR "/src/Services/DTA.FRS"
RUN dotnet build "DTA.FRS.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DTA.FRS.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DTA.FRS.dll"]
