{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "srs.fullname" .) .Values.serviceAccount.name | trimSuffix "-" }}
  namespace: default  # Make sure the namespace matches where you want to deploy
{{- end }}