apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |-
    {{ .Files.Get "files/nginx.conf" | nindent 4 }}
  index.html: |-
    {{ .Files.Get "files/index.html" | nindent 4 }}
