apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        error_log  /var/log/nginx/error.log;

        server {
            listen 80;

            location /grafana/ {
                proxy_pass http://grafana:3000/;
            }

            location /prometheus/ {
                proxy_pass http://prometheus:9090/;
            }

            location /loki/ {
                proxy_pass http://loki:3100/;
            }

            location /tempo/ {
                proxy_pass http://tempo:3200/;
            }

            location /otel-collector/ {
                proxy_pass http://otel-collector:4317/;
            }

            # Add more location blocks for other services as needed
        }
    }

