# Default values for lgtm.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: donasnave/dta-lgtm
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  - name: GF_SERVER_ROOT_URL
    value: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
  - name: GF_SERVER_SERVE_FROM_SUB_PATH
    value: "true"
  - name: GF_SERVER_SERVE_HTTP_PORT
    value: 3000
  - name: GF_AUTH_ANONYMOUS_ENABLED
    value: "true"

service:
  type: ClusterIP
  ports:
    - name: grpc-collector
      port: 4317
      targetPort: 4317
    - name: http-collector
      port: 4318
      targetPort: 4318
    - name: grafana
      port: 3000
      targetPort: 3000

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: "10Gi"

volumeMounts:
  - name: grafana-data
    mountPath: /var/lib/grafana

volumes:
  - name: grafana-data
    persistentVolumeClaim:
      claimName: "grafana-data-pvc"

serviceAccount:
  create: true
  name: "lgtm-api-access"

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}

imagePullSecrets: []
nodeSelector: {}
affinity: {}
tolerations: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi