# Default values for lgtm.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: docker.io/library/dta-lgtm
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: grafana
      port: 3000
      targetPort: 3000

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: localhost
      paths:
        - path: /grafana
          pathType: Prefix
          service:
            name: grafana
            port: 3000
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: "10Gi"

grafanaIni: |
  [server]
  root_url = %(protocol)s://%(domain)s/grafana/
  serve_from_sub_path = true

volumeMounts:
  - name: grafana-data
    mountPath: /var/lib/grafana
  - name: grafana-ini
    mountPath: /etc/grafana/grafana.ini
    subPath: grafana.ini

volumes:
  - name: grafana-data
    persistentVolumeClaim:
      claimName: "grafana-data-pvc"
  - name: grafana-ini
    configMap:
      name: "grafana-configmap"

serviceAccount:
  create: true
  name: "lgtm-api-access"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80