# Default values for lgtm.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: donasnave/dta-lgtm
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  ports:
    - name: grpc-collector
      port: 4317
      targetPort: 4317
    - name: http-collector
      port: 4318
      targetPort: 4318
    - name: grafana
      port: 3000
      targetPort: 3000

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: "10Gi"

volumeMounts:
  - name: grafana-data
    mountPath: /var/lib/grafana
  - name: grafana-ini
    mountPath: /etc/grafana/grafana.ini
    subPath: grafana.ini

volumes:
  - name: grafana-data
    persistentVolumeClaim:
      claimName: "grafana-data-pvc"
  - name: grafana-ini
    configMap:
      name: "grafana-configmap"

serviceAccount:
  create: true
  name: "lgtm-api-access"

autoscaling:
  enabled: false

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi