FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["DTA.SRS/DTA.SRS.csproj", "DTA.JIT.SRS/"]
COPY ["DTA.Extensions/DTA.Extensions.csproj", "DTA.Extensions/"]
COPY ["DTA.Models/DTA.Models.csproj", "DTA.Models/"]
RUN dotnet restore "DTA.SRS/DTA.SRS.csproj"

COPY . .
WORKDIR "/src/DTA.SRS"
RUN dotnet build "DTA.SRS.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DTA.SRS.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DTA.SRS.dll"]
