version: '3.7'

volumes:
  grafana_storage:
  prometheus_data:
  postgres:
  pgadmin:

networks:
  stack-network:
  
services:
  fus-service:
    image: fus-service
    container_name: fus-service
    build:
      context: ../../DTA/Services
      dockerfile: DTA.JIT.FUS/Dockerfile
    environment:
      - "DAT_JIT_FUS_Logging__LogLevel__Default=Debug"
      - "DAT_JIT_FUS_Logging__LogLevel__OpenTelemetry=Debug"
    ports:
      - "15001:8080"
    networks:
      - stack-network

  srs-service:
    image: srs-service
    container_name: srs-service
    build:
      context: ../../DTA/Services
      dockerfile: DTA.JIT.SRS/Dockerfile
    environment:
      - "DAT_JIT_SRS_Logging__LogLevel__Default=Debug"
      - "DAT_JIT_FUS_Logging__LogLevel__OpenTelemetry=Debug"
    ports:
      - "15002:8080"
    networks:
      - stack-network

  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-stack
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: unless-stopped
    networks:
      - stack-network
