version: '3.7'

volumes:
  grafana_storage:
  prometheus_data:
  postgres:

networks:
  stack-network:
  
services:
  # fus-jit-service:
  #   image: dta-fus:jit-latest
  #   container_name: fus-service
  #   build:
  #     context: ../../DTA
  #     dockerfile: Services/DTA.FUS/Dockerfile-JIT
  #   ports:
  #     - "12002:8080"
  #   environment:
  #     - "DTA_JIT_FUS_Logging__LogLevel__Default=Debug"
  #     - "DTA_JIT_FUS_Logging__LogLevel__OpenTelemetry=Debug"
  #     - "DTA_JIT_FUS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
  #   networks:
  #     - stack-network

  # srs-jit-service:
  #   image: dta-srs:jit-latest
  #   container_name: srs-jit-service
  #   build:
  #     context: ../../DTA
  #     dockerfile: Services/DTA.SRS/Dockerfile-JIT
  #   environment:
  #     - "DTA_JIT_SRS_Logging__LogLevel__Default=Debug"
  #     - "DTA_JIT_SRS_Logging__LogLevel__OpenTelemetry=Debug"
  #     - "DTA_JIT_SRS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - stack-network

  fus-aot-service:
    image: dta-fus:aot-latest
    container_name: fus-aot-service
    build:
      context: ../../DTA
      dockerfile: Services/DTA.FUS/Dockerfile-AOT
    ports:
      - "12002:8080"
    environment:
      - "DTA_AOT_FUS_Logging__LogLevel__Default=Debug"
      - "DTA_AOT_FUS_Logging__LogLevel__OpenTelemetry=Debug"
      - "DTA_AOT_FUS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
      - "DTA_AOT_FUS_ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=FUS;Username=postgres;Password=postgres;"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - stack-network

  srs-aot-service:
    image: dta-srs:aot-latest
    container_name: srs-aot-service
    build:
      context: ../../DTA
      dockerfile: Services/DTA.SRS/Dockerfile-AOT
    ports:
      - "12001:8080"
    environment:
      - "DTA_AOT_SRS_Logging__LogLevel__Default=Debug"
      - "DTA_AOT_SRS_Logging__LogLevel__OpenTelemetry=Debug"
      - "DTA_AOT_SRS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
    networks:
      - stack-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - stack-network

  otel-lgtm:
    # build:
    #   context: ../../Tools/LGTM
    #   dockerfile: ./Dockerfile
    image: donasnave/dta-lgtm:latest
    volumes:
      - ./configuration/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: unless-stopped
    networks:
      - stack-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - stack-network

  proxy:
    image: nginx:alpine
    restart: always
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./configuration/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./configuration/proxy/www:/usr/share/nginx/html/custom 
    networks:
      stack-network: