version: '3.7'

volumes:
  grafana_storage:
  prometheus_data:
  postgres:

networks:
  stack-network:
  
services:
  fus-jit-service:
    image: dta-fus:jit-latest
    container_name: fus-service
    build:
      context: ../../DTA
      dockerfile: Services/DTA.FUS/Dockerfile-JIT
    environment:
      - "DTA_JIT_FUS_Logging__LogLevel__Default=Debug"
      - "DTA_JIT_FUS_Logging__LogLevel__OpenTelemetry=Debug"
      - "DTA_JIT_FUS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
    networks:
      - stack-network

  srs-jit-service:
    image: dta-srs:jit-latest
    container_name: srs-service
    build:
      context: ../../DTA
      dockerfile: Services/DTA.SRS/Dockerfile-JIT
    environment:
      - "DTA_JIT_SRS_Logging__LogLevel__Default=Debug"
      - "DTA_JIT_SRS_Logging__LogLevel__OpenTelemetry=Debug"
      - "DTA_JIT_SRS_OpenTelemetrySettings__ExporterEndpoint=http://otel-lgtm:4317"
    networks:
      - stack-network

  otel-lgtm:
    build:
      context: ../../Tools/LGTM
      dockerfile: ./Dockerfile
    volumes:
      - ./configuration/grafana-provisioning/grafana.ini:/etc/grafana/grafana.ini
      - ./configuration/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
    restart: unless-stopped
    networks:
      - stack-network

  proxy:
    image: nginx:alpine
    restart: always
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./configuration/proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./configuration/proxy/www:/usr/share/nginx/html/custom 
    networks:
      stack-network: