apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer # Change to NodePort or ClusterIP if LoadBalancer is not supported
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
