apiVersion: v1
kind: Service
metadata:
  name: srs-service
spec:
  selector:
    app: srs-service
  ports:
  - protocol: TCP
    port: 80 # Target port should match the container's exposed port
    targetPort: 8080