apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
      - name: grafana-port
        protocol: TCP
        port: 3000
        targetPort: 3000
      - name: otel-port
        protocol: TCP
        port: 4317
        targetPort: 4317