apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 55681
    targetPort: 55681
    protocol: TCP
  selector:
    app: otel-collector
